# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "millennial-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-112060364-2"

menu:
  - { name: "Tech", url: "tech" }
  - { name: "Stories", url: "stories" }
  - { name: "Holidays", url: "holdiays" }
  - { name: "Posts", url: "posts" }
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "twitter", link: "https://twitter.com/paululele" }
  - { icon: "instagram", link: "https://instagram.com/paululele" }
  - { icon: "envelope", link: "mailto:mirco.pyrtek@icloud.com" }
  - { icon: "rss-square", link: "rss-feed.xml" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
